name: extplane-panel
version: "2.1.0-git"
summary: External networked panel for flight simulators
description: |
  External networked panel for flight simulators such
  as X-Plane, FlightGear and Condor
base: core20
confinement: devmode
grade: stable

parts:
  extplane:
    source: https://github.com/vranki/ExtPlane.git
    plugin: dump

  extplane-panel:
    build-packages: [qt5-default]
    source: .
    plugin: make
    override-build: |
      set -eux
      qmake -set prefix $SNAPCRAFT_PART_INSTALL
      qmake -r
      snapcraftctl build
    after: [extplane]
    build-packages:
      - libqt5svg5-dev
      - qtdeclarative5-dev
    stage-packages:
      - qml-module-qt-labs-settings
      - qml-module-qtquick-layouts
      - qml-module-qtquick-window2
      - qml-module-qtquick2
      - qml-module-qtquick-dialogs
      - qml-module-qtquick-controls
      - qml-module-qtquick-shapes
      - qml-module-qt-labs-folderlistmodel

apps:
  extplane-panel:
    command: extplane-panel
    adapter: full
    plugs: [x11, network, network-bind]
